Repository PadWorld-Entertainment/worldofpadman, pull requests merged in 2023-11, with the labels that each got.

#176 Better hit sound feedback
  code/cgame/cg_local.h
  code/cgame/cg_main.c
  code/cgame/cg_playerstate.c
  code/game/bg_public.h
  code/game/g_combat.c
  code/ui/ui_preferences.c
  wop/sound.pk3dir/sound/feedback/hit_noshield.wav
  wop/sound.pk3dir/sound/feedback/hit_shield.wav
  wop/sound.pk3dir/sound/feedback/hit_team.ogg
Labels: enhancement

#199 GENDER: Enable the user to select the gender
  code/cgame/cg_event.c
  code/cgame/cg_local.h
  code/cgame/cg_players.c
  code/client/cl_main.c
  code/game/bg_public.h
  code/game/g_bot.c
  code/game/g_client.c
  code/ui/ui_playersettings.c
Labels: enhancement, help wanted

#140 Fixed SuperPad anaglyph 3D glasses colors
  wop/models.pk3dir/models/wop_players/padman/icon_superpad.tga
  wop/models.pk3dir/models/wop_players/padman/icon_superpad_blue.tga
  wop/models.pk3dir/models/wop_players/padman/icon_superpad_red.tga
  wop/models.pk3dir/models/wop_players/padman/superpad_head.tga
  wop/models.pk3dir/models/wop_players/padman/superpad_head_blue.tga
  wop/models.pk3dir/models/wop_players/padman/superpad_head_red.tga
Labels: good first issue

#158 One Lolly CTL for World of Padman
  code/botlib/be_ai_goal.c
  code/cgame/cg_consolecmds.c
  code/cgame/cg_draw.c
  code/cgame/cg_event.c
  code/cgame/cg_info.c
  code/cgame/cg_local.h
  code/cgame/cg_main.c
  code/cgame/cg_players.c
  code/cgame/cg_playerstate.c
  code/cgame/cg_predict.c
  code/cgame/cg_scoreboard.c
  code/cgame/cg_servercmds.c
  code/game/bg_misc.c
  code/game/bg_public.h
  code/game/g_active.c
  code/game/g_cmds.c
  code/game/g_combat.c
  code/game/g_ctlitems.c
  code/game/g_gameinfo.c
  code/game/g_items.c
  code/game/g_spawn.c
  code/game/g_target.c
  code/game/g_team.c
  code/ui/ui_callvote.c
  code/ui/ui_help.c
  code/ui/ui_servers.c
  code/ui/ui_startserver.c
  wop/gfx.pk3dir/icons/hud_lolly_neutral1.png
  wop/gfx.pk3dir/icons/hud_lolly_neutral2.png
  wop/gfx.pk3dir/icons/hud_lolly_neutral3.png
  wop/menu.pk3dir/menu/help/1lctl.png
  wop/menu.pk3dir/menu/info/1lctl.png
  wop/models.pk3dir/models/ctl/lollipop_neutral.md3
  wop/models.pk3dir/models/ctl/n_chromic.tga
  wop/models.pk3dir/models/ctl/n_lollipop.tga
  wop/models.pk3dir/models/ctl/n_sticker_ribbon.tga
  wop/scripts.pk3dir/scripts/wop_gamemodels.shader
  wop/scripts.pk3dir/scripts/wop_icons.shader
  wop/scripts.pk3dir/scripts/wop_maps.arena
Labels: enhancement
